const $ = (selector) => document.querySelector(selector);
let overview = null;

function showError(message) { const box = $('#error'); box.textContent = message; box.hidden = false; }
function formatNumber(value) { return Number(value || 0).toLocaleString('ru-RU'); }
function metric(label, value, note = '') { return `<div class="metric"><span>${label}</span><strong>${formatNumber(value)}</strong>${note ? `<small>${note}</small>` : ''}</div>`; }
function renderMetrics() { const summary = overview.summary || {}; $('#metrics').innerHTML = [metric('Сотрудников', summary.employee_count), metric('Средний прогресс', `${summary.average_progress_pct || 0}%`, 'по карьерным маршрутам'), metric('Без следующего шага', summary.without_recommendation || 0, 'требуют внимания'), metric('Активностей завершено', summary.completed_activities || 0)].join(''); }
function renderEmployees() { const query = ($('#search').value || '').toLowerCase(); const department = $('#department').value; const rows = (overview.employees || []).filter((item) => (!department || item.department === department) && `${item.full_name} ${item.role} ${item.grade}`.toLowerCase().includes(query)); $('#employees').innerHTML = rows.map((item) => { const progress = Number(item.progress_pct || 0); const warning = !item.top_action || progress < 35; return `<tr class="employee-row" data-employee-id="${item.employee_id}"><td><div class="person"><div class="avatar">${item.full_name.slice(0,1)}</div><div><b>${item.full_name}</b><span class="muted">${item.department}</span></div></div></td><td>${item.role}<span class="muted">${item.grade} → ${item.target_grade || '—'}</span></td><td><div class="progress"><div class="track"><div class="fill" style="width:${progress}%"></div></div><b>${progress}%</b></div></td><td><span class="signal ${warning ? 'warn' : ''}">${warning ? 'Нужен разбор' : 'В маршруте'}</span></td><td>${item.top_action || 'Нет рекомендации'}<span class="muted">${item.target_role || ''}</span></td></tr>`; }).join('') || '<tr><td colspan="5">Сотрудники не найдены</td></tr>'; document.querySelectorAll('.employee-row').forEach((row) => row.onclick = () => openEmployee(row.dataset.employeeId)); }
function detailMarkup(data) { const person = data.employee; const trajectory = data.trajectory; const gaps = (data.gaps || []).filter((item) => item.gap > 0).slice(0, 6); const history = (data.history || []).slice(0, 5); return `<div class="detail-head"><div class="avatar large">${person.full_name.slice(0,1)}</div><div><p class="eyebrow">Профиль сотрудника</p><h2>${person.full_name}</h2><p>${person.role} · ${person.grade} · ${person.department}</p></div></div><div class="detail-stats"><div><span>Прогресс</span><b>${trajectory.progress_pct}%</b></div><div><span>Цель</span><b>${trajectory.target_role} · ${trajectory.target_grade}</b></div><div><span>Coins</span><b>${formatNumber(data.gamification?.coins_balance)}</b></div><div><span>Стаж</span><b>${person.tenure_months} мес.</b></div></div><section><h3>Навыковые разрывы</h3>${gaps.length ? `<div class="detail-list">${gaps.map((gap) => `<div><span>${gap.skill_name}</span><b>${gap.current_level}/${gap.required_level}</b><small>${gap.critical ? 'Критичный навык' : 'Зона развития'}</small></div>`).join('')}</div>` : '<p class="muted">Разрывов не найдено.</p>'}</section><section><h3>Ближайшие рекомендации</h3>${(data.recommendations || []).slice(0, 3).map((item) => `<div class="recommendation"><b>${item.title}</b><span>+${item.reward_coins || 60} Coins · ${item.duration_hours} ч</span><small>${(item.reasons || []).join(' · ')}</small></div>`).join('') || '<p class="muted">Нет активной рекомендации.</p>'}</section><section><h3>Последняя активность</h3>${history.length ? `<div class="detail-list">${history.map((item) => `<div><span>${item.event_title}</span><b>${item.status}</b><small>${item.date}</small></div>`).join('')}</div>` : '<p class="muted">История пока пуста.</p>'}</section>`; }
async function openEmployee(employeeId) { const modal = $('#employee-modal'); const detail = $('#employee-detail'); modal.hidden = false; detail.innerHTML = '<p class="muted">Загружаю профиль…</p>'; try { const response = await fetch(`/api/hr/employees/${employeeId}`); if (!response.ok) throw new Error('Профиль не найден'); detail.innerHTML = detailMarkup(await response.json()); } catch (error) { detail.innerHTML = `<p class="error">${error.message}</p>`; } }
function renderBars() { const render = (selector, items, valueKey, max = 1) => { $(selector).innerHTML = (items || []).slice(0, 6).map((item) => { const value = Number(item[valueKey] || item.count || 0); const width = Math.max(8, Math.round(value / max * 100)); return `<div class="bar-row"><div><div class="bar-label"><span>${item.name || item.skill || item.status}</span><b>${formatNumber(value)}</b></div><div class="bar-track"><div class="bar-fill" style="width:${width}%"></div></div></div></div>`; }).join('') || '<p>Нет данных</p>'; }; const gaps = overview.top_skill_gaps || []; const maxGap = Math.max(...gaps.map((item) => Number(item.count || item.employees || 0)), 1); render('#gaps', gaps, 'count', maxGap); render('#participation', overview.participation || [], 'count', Math.max(...(overview.participation || []).map((item) => Number(item.count || 0)), 1)); }
function render() { renderMetrics(); renderEmployees(); renderBars(); $('#updated').textContent = `Обновлено: ${new Date().toLocaleTimeString('ru-RU')} · ${overview.source === 'employee server' ? 'синхронизировано с employee-сайтом' : 'локальная сводка'}`; }
async function loadOverview() { try { const response = await fetch('/api/hr/overview'); if (!response.ok) throw new Error('Не удалось загрузить HR-сводку'); overview = await response.json(); const departments = [...new Set((overview.employees || []).map((item) => item.department).filter(Boolean))].sort(); $('#department').innerHTML = '<option value="">Все подразделения</option>' + departments.map((item) => `<option>${item}</option>`).join(''); render(); } catch (error) { showError(`${error.message}. Проверьте, что HR-сервер запущен.`); } }
function enter() { if ($('#hr-code').value.trim().toUpperCase() !== 'HR-DEMO-2026') return showError('Проверьте HR-код доступа'); $('#login').hidden = true; $('#dashboard').hidden = false; loadOverview(); setInterval(loadOverview, 15000); }
$('#login-button').onclick = enter; $('#hr-code').onkeydown = (event) => { if (event.key === 'Enter') enter(); }; $('#refresh').onclick = loadOverview; $('#search').oninput = () => overview && renderEmployees(); $('#department').onchange = () => overview && renderEmployees(); $('#close-modal').onclick = () => { $('#employee-modal').hidden = true; }; $('#employee-modal').onclick = (event) => { if (event.target.id === 'employee-modal') event.currentTarget.hidden = true; };
